"""``salvager login wallapop`` — Story 2.9 (FR41, NFR-S2, AR21).

Opens a real Chromium browser at Wallapop's login page (via the
``wallapop_browser`` adapter). The operator completes login + 2FA
manually. As soon as a logged-in session cookie is observed, this
command serializes every cookie from the browser context into Netscape
``cookies.txt`` format, writes it to ``data_dir/auth/wallapop_cookies.txt``
with mode ``0600``, and exits.

Layering
--------
The Playwright SDK lives entirely in
``adapters/wallapop_browser/`` (adapter discipline, NFR-M1). This
command owns everything else: the TTY gate, the Netscape serializer,
the atomic write, and the 0600 enforcement.

**Why Netscape, not JSON.** The adapter in
``adapters/wallapop_api/cookies.py`` consumes Netscape ``cookies.txt``
— same format ``curl``/``wget`` produce — so the operator can
hand-edit the file or replace it via any cookie tooling on disk.

Exit codes (FR48)
-----------------
``0`` success • ``1`` non-TTY • ``4`` login timeout or browser-not-installed.
"""

from __future__ import annotations

import asyncio
import sys
from collections.abc import Callable, Coroutine, Iterable
from pathlib import Path
from typing import Any

from salvager.adapters.wallapop_browser import (
    BrowserLoginTimeout,
    BrowserNotInstalled,
    CookieDict,
    capture_wallapop_cookies,
)
from salvager.observability.logging import get_logger
from salvager.observability.styling import render_prose

#: Default wall-clock budget for the operator to complete login + 2FA.
DEFAULT_LOGIN_TIMEOUT_S: int = 300

#: Wallapop's login entry point. The operator may navigate elsewhere
#: during the SSO flow; the adapter only checks for the session cookie.
_WALLAPOP_LOGIN_URL: str = "https://es.wallapop.com/login"

#: Test seam: an async callable that returns the cookies observed inside
#: the browser session, OR raises on failure. Production uses the
#: Playwright-backed :func:`capture_wallapop_cookies`; tests substitute
#: a fake that returns canned cookie sets.
CookieCapture = Callable[[str, float], Coroutine[Any, Any, list[CookieDict]]]


def run(
    data_dir: Path,
    *,
    timeout_s: int = DEFAULT_LOGIN_TIMEOUT_S,
    capture: CookieCapture | None = None,
    isatty: Callable[[], bool] = sys.stdin.isatty,
) -> int:
    """Capture a Wallapop session cookie via headed Chromium.

    Returns a CLI exit code. Never raises through the typer boundary —
    every failure is rendered via :func:`render_prose` first.
    """
    log = get_logger("cli.login_wallapop")

    if not isatty():
        render_prose(
            "login wallapop requires an interactive terminal",
            style="error",
        )
        return 1

    cookies_path = data_dir / "auth" / "wallapop_cookies.txt"
    cookies_path.parent.mkdir(parents=True, exist_ok=True)

    render_prose("Opening browser for manual login...", style="info")

    capture_fn = capture if capture is not None else capture_wallapop_cookies

    try:
        cookies = asyncio.run(capture_fn(_WALLAPOP_LOGIN_URL, float(timeout_s)))
    except BrowserLoginTimeout:
        log.error("login_wallapop_timeout", extra={"timeout_s": timeout_s})
        render_prose(
            "login timeout: no cookie captured",
            style="error",
            hint="re-run salvager login wallapop when ready",
        )
        return 4
    except BrowserNotInstalled as exc:
        log.exception("login_wallapop_browser_missing", extra={"detail": str(exc)})
        render_prose(
            "Chromium browser not installed for Playwright",
            style="error",
            hint="run `uv run playwright install chromium` and retry",
        )
        return 4

    _write_cookies_atomically(cookies_path, cookies)
    _enforce_0600(cookies_path)

    log.info(
        "login_wallapop_success",
        extra={
            "cookies_path": str(cookies_path),
            "cookie_count": len(cookies),
        },
    )
    render_prose("Cookie captured (mode 0600 verified)", style="success")
    return 0


# ─────────────────────────────────────────────────────────────────────────
# Netscape serializer + atomic write + permission enforcement
# ─────────────────────────────────────────────────────────────────────────


_NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by salvager login wallapop.\n"
    "# https://curl.se/docs/http-cookies.html\n"
)


def _serialize_to_netscape(cookies: Iterable[CookieDict]) -> str:
    """Render a Playwright cookies list in Netscape ``cookies.txt`` form.

    Each non-empty row has the standard 7 tab-separated fields:

        domain  include_subs  path  secure  expiry  name  value

    Rows whose ``name`` or ``value`` is missing are dropped — they
    would never round-trip through the adapter's parser anyway.
    """
    lines: list[str] = []
    for cookie in cookies:
        name = cookie.get("name")
        value = cookie.get("value")
        if not name or value is None:
            continue
        domain = cookie.get("domain", "")
        include_subs = "TRUE" if domain.startswith(".") else "FALSE"
        path = cookie.get("path") or "/"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        # Playwright reports a float epoch; -1 = session cookie. Netscape
        # uses 0 to mean "no expiry / session cookie".
        raw_expires = cookie.get("expires", 0) or 0
        expires = max(0, int(raw_expires))
        lines.append("\t".join([domain, include_subs, path, secure, str(expires), name, value]))
    body = "\n".join(lines)
    return _NETSCAPE_HEADER + (body + "\n" if body else "")


def _write_cookies_atomically(path: Path, cookies: Iterable[CookieDict]) -> None:
    """Write ``cookies`` to ``path`` via temp-file + rename.

    The rename is the atomic step: readers see either the old contents
    or the complete new file, never a half-written one.
    """
    contents = _serialize_to_netscape(cookies)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(contents, encoding="utf-8")
    # Constrain the temp file BEFORE the rename so the final inode is
    # never world-readable, even for a moment.
    tmp.chmod(0o600)
    tmp.replace(path)


def _enforce_0600(path: Path) -> None:
    """Re-stat the file post-write and refuse to leave it world-readable.

    ``write_text`` on some filesystems honours the umask, which can
    leak through to the rename even after the temp-file chmod above.
    Belt-and-braces: chmod here too. The verify-on-read step lives in
    Story 2.11.
    """
    path.chmod(0o600)
    actual = path.stat().st_mode & 0o777
    if actual != 0o600:
        # Filesystem doesn't support POSIX modes (e.g. FAT32 mount). We
        # surface this loudly so the operator moves the data_dir to a
        # POSIX filesystem rather than silently shipping a 0644 secret.
        raise OSError(
            f"could not enforce mode 0600 on {path} (observed {oct(actual)}); "
            "is data_dir on a non-POSIX filesystem?"
        )


__all__ = [
    "DEFAULT_LOGIN_TIMEOUT_S",
    "run",
]
